name             'kubernetes'
maintainer       'Maxim Filatov'
maintainer_email 'bregor@evilmartians.com'
license          'MIT'
description      'Installs/Configures google kubernetes'
long_description 'Google Kubernetes installer for deb-based distros with docker'
version          '0.0.2'

depends 'apt'
depends 'systemd', '>= 3.1'
depends 'etcd', '~> 4.1'
depends 'network_interfaces_v2'
depends 'tar'
depends 'firewall'
depends 'ufw'
