default['kubernetes']['kubelet']['image_gc_low_threshold']       = '70'
default['kubernetes']['kubelet']['image_gc_high_threshold']      = '80'
default['kubernetes']['kubelet']['cadvisor_port']                = 0
default['kubernetes']['kubelet']['v']                            = 2
default['kubernetes']['kubelet']['register_node']                = 'true'
default['kubernetes']['kubelet']['anonymous_auth']               = 'false'
default['kubernetes']['kubelet']['client_ca_file']               = '/etc/kubernetes/ssl/ca.pem'
default['kubernetes']['kubelet']['authorization_mode']           = 'Webhook' # Other possible values: 'AlwaysAllow'
default['kubernetes']['kubelet']['fail_swap_on']                 = 'false'
default['kubernetes']['kubelet']['cluster_dns']                  = node['kubernetes']['cluster_dns']
default['kubernetes']['kubelet']['allow_privileged']             = true
default['kubernetes']['kubelet']['pod_manifest_path']            = '/etc/kubernetes/manifests'
default['kubernetes']['kubelet']['node_status_update_frequency'] = '4s'
default['kubernetes']['kubelet']['kubeconfig']                   = '/etc/kubernetes/kubelet.yaml'
default['kubernetes']['kubelet']['authentication_token_webhook'] = nil # set nil if key doesn't have a parameters
default['kubernetes']['kubelet']['bootstrap_kubeconfig']         = '/etc/kubernetes/kubeconfig-bootstrap.yaml'
default['kubernetes']['kubelet']['feature_gates']                = node['kubernetes']['feature_gates'].join(',')
default['kubernetes']['kubelet']['cert_dir']                     = '/etc/kubernetes/ssl'
default['kubernetes']['kubelet']['network_plugin']               = 'cni'
default['kubernetes']['kubelet']['cni_bin_dir']                  = '/opt/cni/bin'
default['kubernetes']['kubelet']['cni_conf_dir']                 = '/etc/cni/net.d'
default['kubernetes']['kubelet']['cluster_domain']               = node['kubernetes']['cluster_domain']
